run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - .next
    - node_modules

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gocritic
    - gocyclo
    - misspell
    - unparam
    - nakedret
    - prealloc
    - exportloopref

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: true # we might not want to enforce comments on all exported items yet
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - wrapperFunc

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
