ALTER TABLE agents
    ADD COLUMN IF NOT EXISTS role VARCHAR(100) NOT NULL DEFAULT 'developer',
    ADD COLUMN IF NOT EXISTS provider VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS capabilities TEXT[] NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_agents_role ON agents(role);
