-- Migration 028: B-001 Execution Lifecycle Extension (4 -> 6 states)
--
-- Sprint 4 had 4 execution statuses: pending, running, completed, failed.
-- The B-001 brief extends the lifecycle to 6:
--   queued    -> assigned, failed
--   assigned  -> running, failed, queued (operator/recovery return)
--   running   -> review, failed
--   review    -> completed, failed
--   completed -> (terminal)
--   failed    -> (terminal)
--
-- This migration:
--   1. Adds 'queued' and 'review' to the CHECK constraint.
--   2. Renames existing 'pending' rows to 'assigned' (the new name for
--      the "agent has been picked, waiting to start" state).
--   3. (Does NOT yet allow agent_id IS NULL; new `queued` rows are
--      Sprint 5+ work. The model permits `*uuid.UUID` for forward
--      compatibility, but the column remains NOT NULL until a
--      queue-dispatcher endpoint lands.)
--
-- Down-migration is provided as a comment block at the bottom; the
-- migration runner does not currently support down, but the operations
-- are reversible in the same transaction if needed.

BEGIN;

-- Step 1: drop the old CHECK constraint, add a new one with the 6
-- allowed values. The constraint name `executions_status_check` was
-- auto-generated by the original 008 migration (no explicit name was
-- set in the table definition). Defensive: if the name was overridden
-- in a later migration, drop both the implicit and explicit names.
ALTER TABLE executions DROP CONSTRAINT IF EXISTS executions_status_check;

ALTER TABLE executions
    ADD CONSTRAINT executions_status_check
    CHECK (status IN (
        'queued',
        'assigned',
        'running',
        'review',
        'completed',
        'failed'
    ));

-- Step 2: rename existing 'pending' rows to 'assigned'. The state
-- semantics are unchanged: an execution that was 'pending' had an
-- agent assigned and was waiting to start; the new name 'assigned'
-- is more accurate. There are no 'pending' rows in production today
-- (the lifecycle moves quickly through 'assigned' -> 'running'), but
-- long-tail Sprint 4 rows may exist.
UPDATE executions SET status = 'assigned' WHERE status = 'pending';

COMMIT;

-- Down-migration (do not run unless rolling back B-001):
--   BEGIN;
--   UPDATE executions SET status = 'pending' WHERE status = 'assigned';
--   ALTER TABLE executions DROP CONSTRAINT executions_status_check;
--   ALTER TABLE executions
--       ADD CONSTRAINT executions_status_check
--       CHECK (status IN ('pending', 'running', 'completed', 'failed'));
--   COMMIT;
