package service

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"strings"
	"time"

	"github.com/example/project/internal/store"
	"github.com/example/project/internal/validation"
	"go.uber.org/zap"
	"golang.org/x/crypto/bcrypt"
	"github.com/golang-jwt/jwt/v5"
)

// AuthService handles authentication and token generation.
type AuthService struct {
	store store.Store
	log   *zap.Logger
}

func NewAuthService(s store.Store, log *zap.Logger) *AuthService {
	return &AuthService{store: s, log: log}
}

// LoginRequest carries credentials from the login endpoint.
type LoginRequest struct {
	Email    string
	Password string
}

// LoginResult carries the response data from a successful login.
type LoginResult struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int    `json:"expires_in"`
}

// Login authenticates a user by email and password.
func (s *AuthService) Login(req LoginRequest) (*LoginResult, *Error) {
	var errs validation.Errors
	validation.NotEmpty(req.Email, "email", "Email", &errs)
	validation.NotEmpty(req.Password, "password", "Password", &errs)
	validation.Email(req.Email, "email", &errs)
	if errs.HasErrors() {
		return nil, validationError(errs)
	}

	user, err := s.store.Users().GetByEmail(req.Email)
	if err != nil {
		s.log.Warn("login attempt for unknown email", zap.String("email_hash", hashForLog(req.Email)))
		return nil, unauthorized("Invalid email or password")
	}

	// Verify password with bcrypt (constant-time comparison)
	if err := bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(req.Password)); err != nil {
		s.log.Warn("login attempt with wrong password", zap.String("email_hash", hashForLog(req.Email)))
		return nil, unauthorized("Invalid email or password")
	}

	// Generate JWT access token
	accessToken, err := s.generateJWT(user.ID, user.Email, 15*time.Minute)
	if err != nil {
		s.log.Error("failed to generate access token", zap.Error(err))
		return nil, internalError("Failed to generate token")
	}

	// Generate refresh token (longer expiry, stored for validation)
	refreshToken, err := s.generateRefreshToken(user.ID)
	if err != nil {
		s.log.Error("failed to generate refresh token", zap.Error(err))
		return nil, internalError("Failed to generate token")
	}

	return &LoginResult{
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
		ExpiresIn:    900, // 15 minutes in seconds
	}, nil
}

// hashForLog returns a truncated hash of email for logging (prevents PII in logs)
func hashForLog(email string) string {
	h := sha256.Sum256([]byte(email))
	return hex.EncodeToString(h[:8])
}

// ValidateToken validates a bearer token and returns the user ID.
func (s *AuthService) ValidateToken(tokenString string) (string, error) {
	// Parse and validate JWT
	claims := &jwt.MapClaims{}
	token, err := jwt.ParseWithClaims(tokenString, claims, func(token *jwt.Token) (interface{}, error) {
		// Ensure signing method is HS256
		if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, errors.New("unexpected signing method")
		}
		return s.getJWTSecret(), nil
	})

	if err != nil {
		return "", unauthorized("Invalid token")
	}

	if !token.Valid {
		return "", unauthorized("Invalid token")
	}

	// Extract user_id from claims
	userID, ok := (*claims)["user_id"].(string)
	if !ok || userID == "" {
		return "", unauthorized("Invalid token claims")
	}

	return userID, nil
}

// generateJWT creates a signed JWT access token
func (s *AuthService) generateJWT(userID, email string, expiry time.Duration) (string, error) {
	now := time.Now()
	claims := jwt.MapClaims{
		"user_id": userID,
		"email":   email,
		"iat":     now.Unix(),
		"exp":     now.Add(expiry).Unix(),
		"iss":     "ai-software-factory",
		"aud":     "ai-software-factory-api",
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	return token.SignedString(s.getJWTSecret())
}

// generateRefreshToken creates a cryptographically secure refresh token
func (s *AuthService) generateRefreshToken(userID string) (string, error) {
	// Generate 32 bytes of random data
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	token := hex.EncodeToString(b)

	// Store refresh token hash for validation (in production, use Redis with TTL)
	// For now, we'll use a simple approach with the token itself being the reference
	// In production: store hash in store with userID and expiry
	return "rt_" + token, nil
}

// ValidateRefreshToken validates a refresh token and returns the user ID
func (s *AuthService) ValidateRefreshToken(refreshToken string) (string, error) {
	if !strings.HasPrefix(refreshToken, "rt_") {
		return "", unauthorized("Invalid refresh token format")
	}
	// In production: look up stored hash and verify
	// For now, we'll decode and verify the token was generated by us
	tokenPart := strings.TrimPrefix(refreshToken, "rt_")
	if len(tokenPart) != 64 { // 32 bytes = 64 hex chars
		return "", unauthorized("Invalid refresh token")
	}
	// Verify it's valid hex
	if _, err := hex.DecodeString(tokenPart); err != nil {
		return "", unauthorized("Invalid refresh token")
	}
	// In production, look up userID from stored refresh token
	// For now, we'd need to store the mapping
	return "", unauthorized("Refresh token validation requires storage backend")
}

// getJWTSecret returns the JWT signing secret (in production, load from config/env)
func (s *AuthService) getJWTSecret() []byte {
	// TODO: Load from config/env variable
	// For now, use a fixed secret (MUST be changed in production)
	return []byte("dev-secret-change-in-production-min-32-chars")
}

func hashToken(input string) string {
	h := sha256.Sum256([]byte(input))
	return hex.EncodeToString(h[:16])
}
